version: '3.8'

services:
  flask_app1:
    image: my-flask-app
    ports:
      - "8099:8099"
    environment:
      DB_HOST: localhost
      DB_USER: admin
      DB_PASSWORD: Tosvert123#
      DB_NAME: student
    restart: unless-stopped

  flask_app2:
    image: my-flask-app
    ports:
      - "8088:8099"
    environment:
      DB_HOST: localhost
      DB_USER: admin
      DB_PASSWORD: Tosvert123#
      DB_NAME: student
    restart: unless-stopped

  flask_app3:
    image: my-flask-app
    ports:
      - "8090:8099"
    environment:
      DB_HOST: localhost
      DB_USER: admin
      DB_PASSWORD: Tosvert123#
      DB_NAME: student
    restart: unless-stopped


